# Generated by Django 4.1.1 on 2022-09-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTable',
            fields=[
                ('id', models.IntegerField()),
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cost_usd', models.IntegerField()),
                ('cost_rub', models.IntegerField()),
                ('delivery_date', models.CharField(max_length=10)),
            ],
        ),
    ]
